title: Project

tabs:
  content:
    label: Layout
    fields:
      layout:
        label: Page Content
        type: layout
        layouts:
          - "1/2, 1/2"  # Two-column layout
          - "1/1"       # Full-width layout
        fieldsets:
          - heading
          - text
          - image
          - gallery
          
  details:
    label: Details
    fields:
      title:
        label: Title
        type: text

      cover:
        label: Cover Image
        type: files
        multiple: false
        layout: cards
        help: "Select an image to use as the cover of this project."

      authors:
        label: Authors
        type: tags
        help: "Add the names of the authors for this project, separated by commas."
        separator: ","

      date:
        label: Date
        type: date
        format: YYYY

      tags:
        label: Type
        type: tags
        help: "Add a category for this project."
        separator: ","
        max: 1
