title: Project

fields:
  title:
    label: Title
    type: text

  cover:
    label: Cover Image
    type: files
    multiple: false
    layout: cards
    help: "Select an image to use as the cover of this project."

  authors:
    label: Authors
    type: tags
    help: "Add the names of the authors for this project, separated by commas."
    separator: ","

  date:
    label: Date
    type: date
    # display: YYYY

  tags:
    label: Tags
    type: tags
    help: "Add relevant tags or categories for this project."
    separator: ","

  blocks:
    label: Content
    type: blocks
    fieldsets:
      - heading
      - text
      - image
      - gallery
      - quote


