title: Project
options:
  preview: http://68.183.58.246/projects/{{ page.slug }}

tabs:
  content:
    label: Layout
    fields:
      layout:
        label: Project Content
        type: layout
        layouts:
          - "1/2, 1/2"  # Two-column layout
          - "1/1"       # Full-width layout
        fieldsets:
          - heading
          - text
          - image
          - gallery
          - external-link
          
  details:
    label: Details
    columns:
      - width: 1/2
        fields:
          title:
            label: Title
            type: text
          cover:
            label: Cover Image
            type: files
            multiple: false
            layout: cards
            help: "Select an image to use as the cover of this project."
          authors:
            label: Authors
            type: tags
            help: "Add the names of the authors for this project, separated by commas."
            separator: ","
      - width: 1/2
        fields:
          displayAsTextLilypad:
            label: Display as text lilypad
            type: toggle
          lilypadSubtitle:
            label: Lilypad Subtitle
            type: text
          lineAfterSubtitle:
            type: line
          startDate:
            label: Start Date
            type: number
          endDate:
            label: End Date
            type: number
          type:
            label: Type
            type: tags
            help: "Add a category for this project."
            separator: ","
            max: 1
          tags:
            label: Tags
            type: tags
            separator: ","
          lineBeforeHideFromIndex:
            type: line
          hideFromIndex:
            label: Hide from Index
            type: toggle

  filesTab:
    label: Files
    sections:
      allFiles:
        headline: All Files
        type: files
        layout: list
        size: medium
        info: "{{ file.filename }}"
        text: "{{ file.niceSize }}"
