title: Site

sections:
  homepageProjects:
    label: Homepage Projects
    type: fields
    fields:
      homepageProjects:
        label: Lilypads
        type: pages
        layout: cards
        size: tiny
        query: site.find('projects').children.listed
        multiple: true
        info: "{{ page.title }}"
        
  recentProjects:
    label: Recent Projects
    type: pages
    query: site.find('projects').children.listed.limit(5)
    info: "{{ page.title }}"

  pages:
    label: Sections
    type: pages
    max: 3
    template:
      - projects
      - contact
      - about
