title: Site

tabs:
  projectsTab:
    label: Projects
    sections:
      projects:
        label: All Projects
        type: pages
        query: site.find('projects').children
        info: "{{ page.authors }} {{ page.tags }} {{ page.date }}"
        image: page.cover.toFile() ?? page.images.first()
        template:
          - project


  homepageTab:
    label: Homepage
    sections:
      homepageProjects:
        label: Lilypads
        type: pages
        layout: cards
        size: tiny
        query: site.find('projects').children.listed
        multiple: true
        image: page.cover.toFile() ?? page.images.first()
        info: "{{ page.title }}"


  pagesTab:
    label: Pages
    sections:
      pages:
        label: Pages
        type: pages
        max: 3
        template:
          - about  # Uncomment other templates as needed
          # - projects
          # - contact
