title: Site
options:
  preview: http://68.183.58.246

tabs:
  projects:
    label: Projects
    sections:
      projectsQuert:
        label: All Projects
        type: pages
        parent: site.find('projects')
        info: "{{ page.authors }} {{ page.tags }} {{ page.date }}"
        image: page.cover.toFile() ?? page.images.first()
        template: project

  homepageTab:
    label: Lilypads
    sections:
      help:
        type: fields
        fields:
          info:
            label: ' '
            type: info
            text: |
              Choose five projects to populate the lilypads on the homepage. You can also order the projects using the handle in the corner of each project's card.
      homepageProjects:
        label: Lilypads
        type: fields
        fields:
          selectedProjects:
            label: Lilypads
            type: pages
            layout: cards
            size: small
            query: site.find('projects').children.listed
            multiple: true
            max: 5
            sortable: true

  pagesTab:
    label: Pages
    sections:
      pages:
        label: Pages
        type: pages
        max: 2
        template:
          - about
          - contact

  otherTab:
    label: Meta & SEO
    sections:
      seo:
        label: SEO Settings
        type: fields
        fields:
          siteDescription:
            label: Site Description
            type: textarea
            width: 1/1
            help: "Enter a brief description of your site that will show up under the title in search results."
            buttons: false