title: Site
options:
  preview: http://68.183.58.246

tabs:
  projects:
    label: Projects
    sections:
      projectsQuert:
        label: All Projects
        type: pages
        parent: site.find('projects')
        info: "{{ page.authors }} {{ page.tags }} {{ page.date }}"
        image: page.cover.toFile() ?? page.images.first()
        template: project

  homepageTab:
    label: Lilypads
    sections:
      lilypads:
        label: Lilypads
        type: fields
        fields:
          layout:
            label: Layout
            type: layout
            layouts:
              - "1/2, 1/2"  # Two-column layout
              - "1/1"       # Full-width layout
            fieldsets:
              - lilypad

  pagesTab:
    label: Pages
    sections:
      pages:
        label: Pages
        type: pages
        max: 2
        template:
          - about
          - contact

  otherTab:
    label: Metadata
    sections:
      metadata:
        type: fields
        fields:
          socialImage:
            label: Social Image
            type: files
            max: 1
            help: "Social image must be titled `social.png`"
          # siteDescription:
          #   label: Site Description
          #   type: textarea
          #   width: 1/1
          #   help: "Enter a brief description of your site that will show up under the title in search results."
          #   buttons: false